name: unpub_web
description: A web app that uses AngularDart Components
version: 1.0.0
publish_to: none
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  angular: ^6.0.0
  angular_forms: ^3.0.0
  angular_router: ^2.0.0
  markdown: ^3.0.0
  unpub_api:
    path: ../unpub/lib/unpub_api
dev_dependencies:
  build_runner: ^1.11.1+1
  build_web_compilers: ^2.16.3
  webdev: ^2.7.1
