name: unpub_auth
description: An auth tool for unpub.
version: 0.1.0
homepage: https://github.com/bytedance/unpub

environment:
  sdk: '>=2.15.0 <3.0.0'

executables:
  unpub_auth:

dependencies:
  collection: ^1.15.0
  path: ^1.8.1
  http: ^0.13.4
  shelf: ^1.2.0
  http_multi_server: ^3.0.1
  oauth2: ^2.0.0
  args: ^2.3.0
  console: ^4.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
